In [251]:
#%pip install pandas numpy matplotlib seaborn scikit-learn

In [252]:
import pandas as pd

In [253]:
df_carteira_cliente =  pd.read_csv('C:\\Users\\47447309818\\Downloads\\history.csv')

In [254]:
df_carteira_cliente.info()

<class 'pandas.DataFrame'>
RangeIndex: 5634 entries, 0 to 5633
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        5634 non-null   str
 1   gender            5634 non-null   str
 2   SeniorCitizen     5634 non-null   int64
 3   Partner           5634 non-null   str
 4   Dependents        5634 non-null   str
 5   tenure            5634 non-null   str
 6   PhoneService      5634 non-null   str
 7   MultipleLines     5634 non-null   str
 8   InternetService   5634 non-null   str
 9   OnlineSecurity    5634 non-null   str
 10  OnlineBackup      5634 non-null   str
 11  DeviceProtection  5634 non-null   str
 12  TechSupport       5634 non-null   str
 13  StreamingTV       5634 non-null   str
 14  StreamingMovies   5634 non-null   str
 15  Contract          5634 non-null   str
 16  PaperlessBilling  5634 non-null   str
 17  PaymentMethod     5634 non-null   str
 18  MonthlyCharges    5634 non-null   float64
 19  TotalCharges      5356 non-null   float64
 20  Churn             5634 non-null   str
 21  CustomerFeedback  5634 non-null   str
 22  MonthlyIncome     5634 non-null   int64
dtypes: float64(2), int64(2), str(19)
memory usage: 4.0 MB

In [255]:
df_carteira_cliente.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
0,4578-PHJYZ,Male,0,Yes,Yes,52,Yes,No,DSL,No,...,Yes,No,One year,Yes,Electronic check,68.75,3482.85,No,I have been a customer with this internet prov...,6532
1,6289-CPNLD,Male,0,Yes,Yes,33,Yes,No,DSL,No,...,Yes,Yes,One year,Yes,Mailed check,73.90,2405.05,Yes,I've been a customer with this company for ove...,7634
2,2682-KEVRP,Female,1,No,No,22,Yes,No,No,No internet service,...,No internet service,No internet service,One year,Yes,Mailed check,20.05,417.00,No,I have been a customer with this company for 2...,3628
3,5697-GOMBF,Female,1,Yes,Yes,28,No,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Electronic check,35.90,973.65,No,I have been a customer with this internet prov...,7851
4,9717-QEBGU,Male,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.30,144.00,No,I have been using the fiber optic internet ser...,1691

In [256]:
df_carteira_cliente.tail()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,CustomerFeedback,MonthlyIncome
5629,8909-BOLNL,Male,0,No,No,3,Yes,No,No,No internet service,...,No internet service,No internet service,One year,No,Mailed check,21.20,52.05,No,I have been a customer with this company for 3...,8354
5630,2832-KJCRD,Female,0,No,No,38,Yes,Yes,Fiber optic,No,...,Yes,Yes,Month-to-month,Yes,Electronic check,103.65,3988.50,No,I have been a customer with this company for 3...,9308
5631,7975-JMZNT,Male,0,Yes,No,66,Yes,Yes,DSL,Yes,...,Yes,Yes,Two year,No,Bank transfer (automatic),91.70,6075.90,No,I have been a customer with this DSL internet ...,2113
5632,4250-ZBWLV,Male,0,No,No,68,Yes,Yes,Fiber optic,No,...,Yes,Yes,One year,No,Electronic check,108.45,7176.55,Yes,I have been a customer with this company for o...,3904
5633,3915-ODIYG,Male,1,No,No,60,Yes,Yes,DSL,Yes,...,No,Yes,One year,Yes,Electronic check,71.75,4374.55,No,I have been a loyal customer of this internet ...,3016

In [257]:
df_carteira_cliente.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'CustomerFeedback', 'MonthlyIncome'],
      dtype='str')

In [258]:
df_carteira_cliente_traduzido = df_carteira_cliente.copy()
df_carteira_cliente_traduzido = df_carteira_cliente_traduzido.rename(columns={
        'customerID': "id_cliente", 
        'gender': "genero", 
        'SeniorCitizen': "idoso", 
        'Partner': "possui_parceiro", 
        'Dependents': "possui_dependentes",
        'tenure': "tempo_de_contrato", 
        'PhoneService': "servico_telefonico", 
        'MultipleLines': "multiplas_linhas", 
        'InternetService': "servico_de_internet",
        'OnlineSecurity': "seguraca_online", 
        'OnlineBackup': "backup_online", 
        'DeviceProtection': "protecao_de_dispositivos", 
        'TechSupport': "suporte_tecnico",
        'StreamingTV': "streaming_de_tv", 
        'StreamingMovies': "streaming_de_filmes", 
        'Contract': "tipo_de_contrato", 
        'PaperlessBilling': "faturamento_digital",
        'PaymentMethod': "metodo_pagamento", 
        'MonthlyCharges': "cobranca_mensal", 
        'TotalCharges': "cobranca_total", 
        'Churn': "cancelou_contrato",
        'CustomerFeedback': "feedback_cliente", 
        'MonthlyIncome': "renda_mensal"
    })

In [259]:
df_carteira_cliente_traduzido.head()

,id_cliente,genero,idoso,possui_parceiro,possui_dependentes,tempo_de_contrato,servico_telefonico,multiplas_linhas,servico_de_internet,seguraca_online,...,streaming_de_tv,streaming_de_filmes,tipo_de_contrato,faturamento_digital,metodo_pagamento,cobranca_mensal,cobranca_total,cancelou_contrato,feedback_cliente,renda_mensal
0,4578-PHJYZ,Male,0,Yes,Yes,52,Yes,No,DSL,No,...,Yes,No,One year,Yes,Electronic check,68.75,3482.85,No,I have been a customer with this internet prov...,6532
1,6289-CPNLD,Male,0,Yes,Yes,33,Yes,No,DSL,No,...,Yes,Yes,One year,Yes,Mailed check,73.90,2405.05,Yes,I've been a customer with this company for ove...,7634
2,2682-KEVRP,Female,1,No,No,22,Yes,No,No,No internet service,...,No internet service,No internet service,One year,Yes,Mailed check,20.05,417.00,No,I have been a customer with this company for 2...,3628
3,5697-GOMBF,Female,1,Yes,Yes,28,No,No phone service,DSL,No,...,Yes,No,Month-to-month,Yes,Electronic check,35.90,973.65,No,I have been a customer with this internet prov...,7851
4,9717-QEBGU,Male,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,Month-to-month,Yes,Electronic check,70.30,144.00,No,I have been using the fiber optic internet ser...,1691

### Identificando o numero de variaveis Object

In [260]:
object_cols = df_carteira_cliente_traduzido.select_dtypes(include="object").columns.tolist() 
print('Total de variáveis do tipo Object:',len(object_cols))
print("---------------------------------------------")
print(object_cols)

Total de variáveis do tipo Object: 19
---------------------------------------------
['id_cliente', 'genero', 'possui_parceiro', 'possui_dependentes', 'tempo_de_contrato', 'servico_telefonico', 'multiplas_linhas', 'servico_de_internet', 'seguraca_online', 'backup_online', 'protecao_de_dispositivos', 'suporte_tecnico', 'streaming_de_tv', 'streaming_de_filmes', 'tipo_de_contrato', 'faturamento_digital', 'metodo_pagamento', 'cancelou_contrato', 'feedback_cliente']

C:\Users\47447309818\AppData\Local\Temp\ipykernel_1280\3072285953.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  object_cols = df_carteira_cliente_traduzido.select_dtypes(include="object").columns.tolist()

In [261]:
data_dict_object = pd.DataFrame({  # cria um DataFrame resumo (dicionário de dados) apenas para colunas do tipo object

    "variavel": object_cols,  # adiciona uma coluna com os nomes das variáveis do tipo object

    "Amostras (em ordem alfabética)": [", ".join(sorted(df_carteira_cliente_traduzido[col].dropna().astype(str).unique()))  # lista os valores únicos da coluna, ordenados alfabeticamente e separados por vírgula
                                       if df_carteira_cliente_traduzido[col].notna().any() else None  # se a coluna tiver apenas NaN, retorna None
                                       for col in object_cols],  # repete esse processo para cada coluna object

    "Amostras (em ordem de frequência)": [", ".join(df_carteira_cliente_traduzido[col].dropna().astype(str).value_counts().index.tolist())  # lista os valores únicos ordenados pela frequência (mais comum primeiro)
                                          if df_carteira_cliente_traduzido[col].notna().any() else None  # se só tiver NaN, retorna None
                                          for col in object_cols],  # repete para cada coluna object
    
    "qtd_valores_unicos": [df_carteira_cliente_traduzido[col].nunique()  # calcula a quantidade de valores únicos em cada coluna
                           for col in object_cols]

})

# Colocar em ordem alfabética
data_dict_object = data_dict_object.sort_values(
    by="Amostras (em ordem alfabética)",  # ordena o DataFrame com base nos valores das amostras em ordem alfabética
    ascending=True,  # ordem crescente
    na_position="last"  # coloca os valores None no final
).reset_index(drop=True)  # reseta o índice após a ordenação

data_dict_object  # exibe o DataFrame final com o resumo das colunas do tipo object

,variavel,Amostras (em ordem alfabética),Amostras (em ordem de frequência),qtd_valores_unicos
0,feedback_cliente,"""After being a customer for 13 months on a mon...",I have been a customer with this internet prov...,5634
1,tempo_de_contrato,"0, 1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, ...","1, 72, 2, 3, 4, 71, 5, 7, 8, 9, 12, 70, 10, 13...",74
2,id_cliente,"0002-ORFBO, 0003-MKNFE, 0011-IGKFF, 0013-MHZWF...","4578-PHJYZ, 6289-CPNLD, 2682-KEVRP, 5697-GOMBF...",5634
3,metodo_pagamento,"Bank transfer (automatic), Credit card (automa...","Electronic check, Mailed check, Credit card (a...",4
4,servico_de_internet,"DSL, Fiber optic, No","Fiber optic, DSL, No",3
5,genero,"Female, Male","Male, Female",2
6,tipo_de_contrato,"Month-to-month, One year, Two year","Month-to-month, Two year, One year",3
7,seguraca_online,"No, No internet service, Yes","No, Yes, No internet service",3
8,backup_online,"No, No internet service, Yes","No, Yes, No internet service",3
9,protecao_de_dispositivos,"No, No internet service, Yes","No, Yes, No internet service",3
10,suporte_tecnico,"No, No internet service, Yes","No, Yes, No internet service",3
11,streaming_de_tv,"No, No internet service, Yes","No, Yes, No internet service",3
12,streaming_de_filmes,"No, No internet service, Yes","No, Yes, No internet service",3
13,multiplas_linhas,"No, No phone service, Yes","No, Yes, No phone service",3
14,possui_parceiro,"No, Yes","No, Yes",2
15,possui_dependentes,"No, Yes","No, Yes",2
16,faturamento_digital,"No, Yes","Yes, No",2
17,cancelou_contrato,"No, Yes","No, Yes",2
18,servico_telefonico,"No, Yes, no, yes","Yes, No, no, yes",4

In [262]:
acronyms = ["id_cliente", "genero", "possui_parceiro", "possui_dependentes", "tipo_de_contrato", "servico_telefonico", "multiplas_linhas", "servico_de_internet", "seguraca_online", "backup_online", "protecao_de_dispositivos", "suporte_tecnico", "streaming_de_tv", "streaming_de_filmes", "faturamento_digital", "metodo_pagamento", "cancelou_contrato"]
# SideofField possui uma categoria diferente (50), possivelmente é um erro
df_carteira_cliente_traduzido[acronyms] = df_carteira_cliente_traduzido[acronyms].astype("category")

In [263]:
df_carteira_cliente_traduzido.isnull().sum()

id_cliente                    0
genero                        0
idoso                         0
possui_parceiro               0
possui_dependentes            0
tempo_de_contrato             0
servico_telefonico            0
multiplas_linhas              0
servico_de_internet           0
seguraca_online               0
backup_online                 0
protecao_de_dispositivos      0
suporte_tecnico               0
streaming_de_tv               0
streaming_de_filmes           0
tipo_de_contrato              0
faturamento_digital           0
metodo_pagamento              0
cobranca_mensal               0
cobranca_total              278
cancelou_contrato             0
feedback_cliente              0
renda_mensal                  0
dtype: int64

In [264]:
df_carteira_cliente_traduzido.info()  # exibe as primeiras linhas do DataFrame para visualização

<class 'pandas.DataFrame'>
RangeIndex: 5634 entries, 0 to 5633
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_cliente                5634 non-null   category
 1   genero                    5634 non-null   category
 2   idoso                     5634 non-null   int64
 3   possui_parceiro           5634 non-null   category
 4   possui_dependentes        5634 non-null   category
 5   tempo_de_contrato         5634 non-null   str
 6   servico_telefonico        5634 non-null   category
 7   multiplas_linhas          5634 non-null   category
 8   servico_de_internet       5634 non-null   category
 9   seguraca_online           5634 non-null   category
 10  backup_online             5634 non-null   category
 11  protecao_de_dispositivos  5634 non-null   category
 12  suporte_tecnico           5634 non-null   category
 13  streaming_de_tv           5634 non-null   category
 14  streaming_de_filmes       5634 non-null   category
 15  tipo_de_contrato          5634 non-null   category
 16  faturamento_digital       5634 non-null   category
 17  metodo_pagamento          5634 non-null   category
 18  cobranca_mensal           5634 non-null   float64
 19  cobranca_total            5356 non-null   float64
 20  cancelou_contrato         5634 non-null   category
 21  feedback_cliente          5634 non-null   str
 22  renda_mensal              5634 non-null   int64
dtypes: category(17), float64(2), int64(2), str(2)
memory usage: 2.9 MB

In [ ]:
df_carteira_cliente_traduzido[df_carteira_cliente_traduzido["tempo_de_contrato"] == "unknown"]  # exibe as primeiras linhas do DataFrame para visualização

In [265]:
tempo =["tempo_de_contrato"]# converte a coluna "tempo_de_contrato" para o tipo inteiro (int64)
df_carteira_cliente_traduzido[tempo] = (
    df_carteira_cliente_traduzido[tempo]
    .apply(pd.to_numeric, errors="coerce")
    .astype("Int64")
)

In [286]:
df_carteira_cliente_traduzido[df_carteira_cliente_traduzido["tempo_de_contrato"] == pd.isnull()]  # exibe as primeiras linhas do DataFrame para visualização

TypeError: isna() missing 1 required positional argument: 'obj'

In [267]:
for indice_linha in range(len(df_carteira_cliente_traduzido)):
    tmp_contrato = df_carteira_cliente_traduzido.loc[indice_linha, "tempo_de_contrato"]
    cbrc_total = df_carteira_cliente_traduzido.loc[indice_linha, "cobranca_total"]
    cbrc_mensal = df_carteira_cliente_traduzido.loc[indice_linha, "cobranca_mensal"]
    if pd.isnull(tmp_contrato) and pd.isna(cbrc_total):
        df_carteira_cliente_traduzido = df_carteira_cliente_traduzido.drop(indice_linha)
    else:
        df_carteira_cliente_traduzido.at[indice_linha, "tempo_de_contrato"] = round((cbrc_total / cbrc_mensal),0)
df_carteira_cliente_traduzido = df_carteira_cliente_traduzido.reset_index(drop=True)

In [268]:
df_carteira_cliente_traduzido.info()  # exibe as primeiras linhas do DataFrame para visualização

<class 'pandas.DataFrame'>
RangeIndex: 5633 entries, 0 to 5632
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_cliente                5633 non-null   category
 1   genero                    5633 non-null   category
 2   idoso                     5633 non-null   int64
 3   possui_parceiro           5633 non-null   category
 4   possui_dependentes        5633 non-null   category
 5   tempo_de_contrato         5356 non-null   Int64
 6   servico_telefonico        5633 non-null   category
 7   multiplas_linhas          5633 non-null   category
 8   servico_de_internet       5633 non-null   category
 9   seguraca_online           5633 non-null   category
 10  backup_online             5633 non-null   category
 11  protecao_de_dispositivos  5633 non-null   category
 12  suporte_tecnico           5633 non-null   category
 13  streaming_de_tv           5633 non-null   category
 14  streaming_de_filmes       5633 non-null   category
 15  tipo_de_contrato          5633 non-null   category
 16  faturamento_digital       5633 non-null   category
 17  metodo_pagamento          5633 non-null   category
 18  cobranca_mensal           5633 non-null   float64
 19  cobranca_total            5356 non-null   float64
 20  cancelou_contrato         5633 non-null   category
 21  feedback_cliente          5633 non-null   str
 22  renda_mensal              5633 non-null   int64
dtypes: Int64(1), category(17), float64(2), int64(2), str(1)
memory usage: 2.9 MB

In [269]:
df_carteira_cliente_traduzido["tempo_de_contrato"].unique()

<IntegerArray>
[  51,   33,   21,   27,    2,   70,    3, <NA>,   42,   22,   23,    6,    1,
   54,   30,   67,   72,   58,   43,   32,   40,   59,   66,   35,   57,   10,
    9,   14,   50,   61,   71,   48,   28,   53,   24,   68,   11,   31,   60,
   62,   39,   13,   15,   29,   34,   19,   37,   47,   63,    7,   73,   26,
   55,    4,   45,   52,    8,   25,   74,   20,   65,   17,   41,   46,   12,
   49,    5,   18,   36,   69,   64,   75,   16,   44,   56,   76,   38,   77]
Length: 78, dtype: Int64

Empty DataFrame
Columns: [id_cliente, genero, idoso, possui_parceiro, possui_dependentes, tempo_de_contrato, servico_telefonico, multiplas_linhas, servico_de_internet, seguraca_online, backup_online, protecao_de_dispositivos, suporte_tecnico, streaming_de_tv, streaming_de_filmes, tipo_de_contrato, faturamento_digital, metodo_pagamento, cobranca_mensal, cobranca_total, cancelou_contrato, feedback_cliente, renda_mensal]
Index: []

[0 rows x 23 columns]

In [271]:
avaliacao = ["feedback_cliente"]  
df_carteira_cliente_traduzido[avaliacao] = df_carteira_cliente_traduzido[avaliacao].astype("string")

In [272]:
df_carteira_cliente_traduzido.info()  # exibe informações sobre o DataFrame, incluindo tipos de dados e contagem de valores não nulos

<class 'pandas.DataFrame'>
RangeIndex: 5633 entries, 0 to 5632
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   id_cliente                5633 non-null   category
 1   genero                    5633 non-null   category
 2   idoso                     5633 non-null   int64
 3   possui_parceiro           5633 non-null   category
 4   possui_dependentes        5633 non-null   category
 5   tempo_de_contrato         5356 non-null   Int64
 6   servico_telefonico        5633 non-null   category
 7   multiplas_linhas          5633 non-null   category
 8   servico_de_internet       5633 non-null   category
 9   seguraca_online           5633 non-null   category
 10  backup_online             5633 non-null   category
 11  protecao_de_dispositivos  5633 non-null   category
 12  suporte_tecnico           5633 non-null   category
 13  streaming_de_tv           5633 non-null   category
 14  streaming_de_filmes       5633 non-null   category
 15  tipo_de_contrato          5633 non-null   category
 16  faturamento_digital       5633 non-null   category
 17  metodo_pagamento          5633 non-null   category
 18  cobranca_mensal           5633 non-null   float64
 19  cobranca_total            5356 non-null   float64
 20  cancelou_contrato         5633 non-null   category
 21  feedback_cliente          5633 non-null   string
 22  renda_mensal              5633 non-null   int64
dtypes: Int64(1), category(17), float64(2), int64(2), string(1)
memory usage: 2.9 MB

In [273]:
df_carteira_cliente_traduzido.columns

Index(['id_cliente', 'genero', 'idoso', 'possui_parceiro',
       'possui_dependentes', 'tempo_de_contrato', 'servico_telefonico',
       'multiplas_linhas', 'servico_de_internet', 'seguraca_online',
       'backup_online', 'protecao_de_dispositivos', 'suporte_tecnico',
       'streaming_de_tv', 'streaming_de_filmes', 'tipo_de_contrato',
       'faturamento_digital', 'metodo_pagamento', 'cobranca_mensal',
       'cobranca_total', 'cancelou_contrato', 'feedback_cliente',
       'renda_mensal'],
      dtype='str')

In [274]:
l_planos = [
    'servico_telefonico',
    'multiplas_linhas', 'servico_de_internet', 'seguraca_online',
    'backup_online', 'protecao_de_dispositivos', 'suporte_tecnico',
    'streaming_de_tv', 'streaming_de_filmes'
] 

for plano in l_planos:
    print(f"Valores da coluna '{plano}':")
    print(df_carteira_cliente_traduzido[plano].unique())
    print("----------------")

Valores da coluna 'servico_telefonico':
['Yes', 'No', 'no', 'yes']
Categories (4, str): ['No', 'Yes', 'no', 'yes']
----------------
Valores da coluna 'multiplas_linhas':
['No', 'No phone service', 'Yes']
Categories (3, str): ['No', 'No phone service', 'Yes']
----------------
Valores da coluna 'servico_de_internet':
['DSL', 'No', 'Fiber optic']
Categories (3, str): ['DSL', 'Fiber optic', 'No']
----------------
Valores da coluna 'seguraca_online':
['No', 'No internet service', 'Yes']
Categories (3, str): ['No', 'No internet service', 'Yes']
----------------
Valores da coluna 'backup_online':
['Yes', 'No', 'No internet service']
Categories (3, str): ['No', 'No internet service', 'Yes']
----------------
Valores da coluna 'protecao_de_dispositivos':
['Yes', 'No internet service', 'No']
Categories (3, str): ['No', 'No internet service', 'Yes']
----------------
Valores da coluna 'suporte_tecnico':
['Yes', 'No internet service', 'No']
Categories (3, str): ['No', 'No internet service', 'Yes']
----------------
Valores da coluna 'streaming_de_tv':
['Yes', 'No internet service', 'No']
Categories (3, str): ['No', 'No internet service', 'Yes']
----------------
Valores da coluna 'streaming_de_filmes':
['No', 'Yes', 'No internet service']
Categories (3, str): ['No', 'No internet service', 'Yes']
----------------

In [275]:
colunas_str = df_carteira_cliente_traduzido.select_dtypes(include=['category', 'string']).columns
df_carteira_cliente_traduzido[colunas_str] = df_carteira_cliente_traduzido[colunas_str].apply(lambda x: x.str.lower())

In [276]:
df_carteira_cliente_traduzido.head()

,id_cliente,genero,idoso,possui_parceiro,possui_dependentes,tempo_de_contrato,servico_telefonico,multiplas_linhas,servico_de_internet,seguraca_online,...,streaming_de_tv,streaming_de_filmes,tipo_de_contrato,faturamento_digital,metodo_pagamento,cobranca_mensal,cobranca_total,cancelou_contrato,feedback_cliente,renda_mensal
0,4578-phjyz,male,0,yes,yes,51,yes,no,dsl,no,...,yes,no,one year,yes,electronic check,68.75,3482.85,no,i have been a customer with this internet prov...,6532
1,6289-cpnld,male,0,yes,yes,33,yes,no,dsl,no,...,yes,yes,one year,yes,mailed check,73.90,2405.05,yes,i've been a customer with this company for ove...,7634
2,2682-kevrp,female,1,no,no,21,yes,no,no,no internet service,...,no internet service,no internet service,one year,yes,mailed check,20.05,417.00,no,i have been a customer with this company for 2...,3628
3,5697-gombf,female,1,yes,yes,27,no,no phone service,dsl,no,...,yes,no,month-to-month,yes,electronic check,35.90,973.65,no,i have been a customer with this internet prov...,7851
4,9717-qebgu,male,0,no,no,2,yes,no,fiber optic,no,...,no,no,month-to-month,yes,electronic check,70.30,144.00,no,i have been using the fiber optic internet ser...,1691

In [277]:
l_planos = [
    'servico_telefonico',
    'multiplas_linhas', 'servico_de_internet', 'seguraca_online',
    'backup_online', 'protecao_de_dispositivos', 'suporte_tecnico',
    'streaming_de_tv', 'streaming_de_filmes'
] 

for plano in l_planos:
    print(f"Valores da coluna '{plano}':")
    print(df_carteira_cliente_traduzido[plano].unique())
    print("----------------")

Valores da coluna 'servico_telefonico':
['yes' 'no']
----------------
Valores da coluna 'multiplas_linhas':
['no' 'no phone service' 'yes']
----------------
Valores da coluna 'servico_de_internet':
['dsl' 'no' 'fiber optic']
----------------
Valores da coluna 'seguraca_online':
['no' 'no internet service' 'yes']
----------------
Valores da coluna 'backup_online':
['yes' 'no' 'no internet service']
----------------
Valores da coluna 'protecao_de_dispositivos':
['yes' 'no internet service' 'no']
----------------
Valores da coluna 'suporte_tecnico':
['yes' 'no internet service' 'no']
----------------
Valores da coluna 'streaming_de_tv':
['yes' 'no internet service' 'no']
----------------
Valores da coluna 'streaming_de_filmes':
['no' 'yes' 'no internet service']
----------------

In [278]:
df_carteira_cliente_silver = df_carteira_cliente_traduzido.copy()

l_colunas = [
'servico_telefonico',
'multiplas_linhas', 
'servico_de_internet', 
'seguraca_online',
'backup_online', 
'protecao_de_dispositivos', 
'suporte_tecnico',
'streaming_de_tv', 
'streaming_de_filmes'
]

In [279]:
for nome_coluna in df_carteira_cliente_silver.columns:
    if nome_coluna in l_colunas:
        for indice_linha in range(len(df_carteira_cliente_silver)):      
            registro_selecionado = df_carteira_cliente_silver.loc[indice_linha, nome_coluna].lower()
            if nome_coluna == "servico_de_internet":
                continue
            elif registro_selecionado != "no" and registro_selecionado != "yes":
                df_carteira_cliente_silver.at[indice_linha, nome_coluna] = "no"

In [280]:
for indice_linha in range(len(df_carteira_cliente_silver)):
    registro_selecionado = df_carteira_cliente_silver.loc[indice_linha, "genero"]
    if registro_selecionado == "male":
        df_carteira_cliente_silver.at[indice_linha, "genero"] = "M"
    elif registro_selecionado == "female":
        df_carteira_cliente_silver.at[indice_linha, "genero"] = "F"

In [281]:
df_carteira_cliente_silver.isnull().sum().sum()

np.int64(554)

In [282]:
df_carteira_cliente_silver.isnull().sum()

id_cliente                    0
genero                        0
idoso                         0
possui_parceiro               0
possui_dependentes            0
tempo_de_contrato           277
servico_telefonico            0
multiplas_linhas              0
servico_de_internet           0
seguraca_online               0
backup_online                 0
protecao_de_dispositivos      0
suporte_tecnico               0
streaming_de_tv               0
streaming_de_filmes           0
tipo_de_contrato              0
faturamento_digital           0
metodo_pagamento              0
cobranca_mensal               0
cobranca_total              277
cancelou_contrato             0
feedback_cliente              0
renda_mensal                  0
dtype: int64

In [283]:
df_carteira_cliente_silver.duplicated().sum()

np.int64(0)

In [284]:
for indice_linha in range(len(df_carteira_cliente_silver)):
    registro_selecionado = df_carteira_cliente_silver.loc[indice_linha, "genero"]
    if registro_selecionado == "male":
        df_carteira_cliente_silver.at[indice_linha, "genero"] = "M"
    elif registro_selecionado == "female":
        df_carteira_cliente_silver.at[indice_linha, "genero"] = "F"

In [285]:
df_carteira_cliente_silver.head()

,id_cliente,genero,idoso,possui_parceiro,possui_dependentes,tempo_de_contrato,servico_telefonico,multiplas_linhas,servico_de_internet,seguraca_online,...,streaming_de_tv,streaming_de_filmes,tipo_de_contrato,faturamento_digital,metodo_pagamento,cobranca_mensal,cobranca_total,cancelou_contrato,feedback_cliente,renda_mensal
0,4578-phjyz,M,0,yes,yes,51,yes,no,dsl,no,...,yes,no,one year,yes,electronic check,68.75,3482.85,no,i have been a customer with this internet prov...,6532
1,6289-cpnld,M,0,yes,yes,33,yes,no,dsl,no,...,yes,yes,one year,yes,mailed check,73.90,2405.05,yes,i've been a customer with this company for ove...,7634
2,2682-kevrp,F,1,no,no,21,yes,no,no,no,...,no,no,one year,yes,mailed check,20.05,417.00,no,i have been a customer with this company for 2...,3628
3,5697-gombf,F,1,yes,yes,27,no,no,dsl,no,...,yes,no,month-to-month,yes,electronic check,35.90,973.65,no,i have been a customer with this internet prov...,7851
4,9717-qebgu,M,0,no,no,2,yes,no,fiber optic,no,...,no,no,month-to-month,yes,electronic check,70.30,144.00,no,i have been using the fiber optic internet ser...,1691